// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/database.dart';
import 'api/models.dart';
import 'api/parsers.dart';
import 'api/simple.dart';
import 'api/sync.dart';
import 'api/tts.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1620461008;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_audire_reader',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiSyncWebDavClientDownloadBytes({
    required WebDavClient that,
    required String remotePath,
  });

  Future<bool> crateApiSyncWebDavClientFileExists({
    required WebDavClient that,
    required String remotePath,
  });

  Future<bool> crateApiSyncWebDavClientMkdir({
    required WebDavClient that,
    required String remotePath,
  });

  Future<WebDavClient> crateApiSyncWebDavClientNew({
    required String url,
    required String user,
    required String pass,
  });

  Future<bool> crateApiSyncWebDavClientRemove({
    required WebDavClient that,
    required String remotePath,
  });

  Future<bool> crateApiSyncWebDavClientTestConnection({
    required WebDavClient that,
  });

  Future<bool> crateApiSyncWebDavClientUploadBytes({
    required WebDavClient that,
    required String remotePath,
    required List<int> bytes,
  });

  Future<void> crateApiDatabaseDeleteBook({required String uuid});

  Future<List<Book>> crateApiDatabaseGetAllBooks();

  Future<List<Chapter>> crateApiDatabaseGetChapters({required String bookUuid});

  Future<List<EdgeVoice>> crateApiTtsGetEdgeVoices();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  void crateApiDatabaseInitDatabase({required String dbPath});

  Future<bool> crateApiTtsInitOfflineTts();

  Future<PlatformInt64> crateApiDatabaseInsertBook({required Book book});

  Future<void> crateApiDatabaseInsertChapters({
    required List<Chapter> chapters,
  });

  Future<bool> crateApiTtsOfflineTtsSpeak({
    required String text,
    required double rate,
  });

  Future<bool> crateApiTtsOfflineTtsStop();

  ParsedBookData crateApiParsersParseDocxFile({required String filePath});

  ParsedBookData crateApiParsersParseEpubFile({
    required String filePath,
    required String documentsDirPath,
  });

  ParsedBookData crateApiParsersParsePdfFile({required String filePath});

  ParsedBookData crateApiParsersParseTxtFile({required String filePath});

  Future<Uint8List> crateApiTtsSynthesizeEdgeTts({
    required String text,
    required String voiceId,
    required double rate,
  });

  Future<Uint8List> crateApiTtsSynthesizeOpenaiTts({
    required String text,
    required String voice,
    required String apiKey,
    required double speed,
  });

  Future<Uint8List> crateApiSyncWebdavDownloadBytes({
    required String remotePath,
  });

  Future<bool> crateApiSyncWebdavFileExists({required String remotePath});

  Future<void> crateApiSyncWebdavInit({
    required String url,
    required String username,
    required String password,
  });

  Future<bool> crateApiSyncWebdavMkdir({required String remotePath});

  Future<bool> crateApiSyncWebdavRemove({required String remotePath});

  Future<bool> crateApiSyncWebdavTestConnection();

  Future<bool> crateApiSyncWebdavUploadBytes({
    required String remotePath,
    required List<int> bytes,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WebDavClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WebDavClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WebDavClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiSyncWebDavClientDownloadBytes({
    required WebDavClient that,
    required String remotePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(remotePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebDavClientDownloadBytesConstMeta,
        argValues: [that, remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebDavClientDownloadBytesConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_download_bytes",
        argNames: ["that", "remotePath"],
      );

  @override
  Future<bool> crateApiSyncWebDavClientFileExists({
    required WebDavClient that,
    required String remotePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(remotePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebDavClientFileExistsConstMeta,
        argValues: [that, remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebDavClientFileExistsConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_file_exists",
        argNames: ["that", "remotePath"],
      );

  @override
  Future<bool> crateApiSyncWebDavClientMkdir({
    required WebDavClient that,
    required String remotePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(remotePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebDavClientMkdirConstMeta,
        argValues: [that, remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebDavClientMkdirConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_mkdir",
        argNames: ["that", "remotePath"],
      );

  @override
  Future<WebDavClient> crateApiSyncWebDavClientNew({
    required String url,
    required String user,
    required String pass,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(user, serializer);
          sse_encode_String(pass, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebDavClientNewConstMeta,
        argValues: [url, user, pass],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebDavClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_new",
        argNames: ["url", "user", "pass"],
      );

  @override
  Future<bool> crateApiSyncWebDavClientRemove({
    required WebDavClient that,
    required String remotePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(remotePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebDavClientRemoveConstMeta,
        argValues: [that, remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebDavClientRemoveConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_remove",
        argNames: ["that", "remotePath"],
      );

  @override
  Future<bool> crateApiSyncWebDavClientTestConnection({
    required WebDavClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebDavClientTestConnectionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebDavClientTestConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_test_connection",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiSyncWebDavClientUploadBytes({
    required WebDavClient that,
    required String remotePath,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
            that,
            serializer,
          );
          sse_encode_String(remotePath, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebDavClientUploadBytesConstMeta,
        argValues: [that, remotePath, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebDavClientUploadBytesConstMeta =>
      const TaskConstMeta(
        debugName: "WebDavClient_upload_bytes",
        argNames: ["that", "remotePath", "bytes"],
      );

  @override
  Future<void> crateApiDatabaseDeleteBook({required String uuid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uuid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseDeleteBookConstMeta,
        argValues: [uuid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseDeleteBookConstMeta =>
      const TaskConstMeta(debugName: "delete_book", argNames: ["uuid"]);

  @override
  Future<List<Book>> crateApiDatabaseGetAllBooks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_book,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseGetAllBooksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseGetAllBooksConstMeta =>
      const TaskConstMeta(debugName: "get_all_books", argNames: []);

  @override
  Future<List<Chapter>> crateApiDatabaseGetChapters({
    required String bookUuid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bookUuid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chapter,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseGetChaptersConstMeta,
        argValues: [bookUuid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseGetChaptersConstMeta =>
      const TaskConstMeta(debugName: "get_chapters", argNames: ["bookUuid"]);

  @override
  Future<List<EdgeVoice>> crateApiTtsGetEdgeVoices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_edge_voice,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTtsGetEdgeVoicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsGetEdgeVoicesConstMeta =>
      const TaskConstMeta(debugName: "get_edge_voices", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiDatabaseInitDatabase({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseInitDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseInitDatabaseConstMeta =>
      const TaskConstMeta(debugName: "init_database", argNames: ["dbPath"]);

  @override
  Future<bool> crateApiTtsInitOfflineTts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTtsInitOfflineTtsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsInitOfflineTtsConstMeta =>
      const TaskConstMeta(debugName: "init_offline_tts", argNames: []);

  @override
  Future<PlatformInt64> crateApiDatabaseInsertBook({required Book book}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_book(book, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseInsertBookConstMeta,
        argValues: [book],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseInsertBookConstMeta =>
      const TaskConstMeta(debugName: "insert_book", argNames: ["book"]);

  @override
  Future<void> crateApiDatabaseInsertChapters({
    required List<Chapter> chapters,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_chapter(chapters, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDatabaseInsertChaptersConstMeta,
        argValues: [chapters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDatabaseInsertChaptersConstMeta =>
      const TaskConstMeta(debugName: "insert_chapters", argNames: ["chapters"]);

  @override
  Future<bool> crateApiTtsOfflineTtsSpeak({
    required String text,
    required double rate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_f_32(rate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTtsOfflineTtsSpeakConstMeta,
        argValues: [text, rate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsOfflineTtsSpeakConstMeta => const TaskConstMeta(
    debugName: "offline_tts_speak",
    argNames: ["text", "rate"],
  );

  @override
  Future<bool> crateApiTtsOfflineTtsStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTtsOfflineTtsStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsOfflineTtsStopConstMeta =>
      const TaskConstMeta(debugName: "offline_tts_stop", argNames: []);

  @override
  ParsedBookData crateApiParsersParseDocxFile({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parsed_book_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiParsersParseDocxFileConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParsersParseDocxFileConstMeta =>
      const TaskConstMeta(debugName: "parse_docx_file", argNames: ["filePath"]);

  @override
  ParsedBookData crateApiParsersParseEpubFile({
    required String filePath,
    required String documentsDirPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(documentsDirPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parsed_book_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiParsersParseEpubFileConstMeta,
        argValues: [filePath, documentsDirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParsersParseEpubFileConstMeta =>
      const TaskConstMeta(
        debugName: "parse_epub_file",
        argNames: ["filePath", "documentsDirPath"],
      );

  @override
  ParsedBookData crateApiParsersParsePdfFile({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parsed_book_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiParsersParsePdfFileConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParsersParsePdfFileConstMeta =>
      const TaskConstMeta(debugName: "parse_pdf_file", argNames: ["filePath"]);

  @override
  ParsedBookData crateApiParsersParseTxtFile({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parsed_book_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiParsersParseTxtFileConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParsersParseTxtFileConstMeta =>
      const TaskConstMeta(debugName: "parse_txt_file", argNames: ["filePath"]);

  @override
  Future<Uint8List> crateApiTtsSynthesizeEdgeTts({
    required String text,
    required String voiceId,
    required double rate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(voiceId, serializer);
          sse_encode_f_64(rate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTtsSynthesizeEdgeTtsConstMeta,
        argValues: [text, voiceId, rate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsSynthesizeEdgeTtsConstMeta =>
      const TaskConstMeta(
        debugName: "synthesize_edge_tts",
        argNames: ["text", "voiceId", "rate"],
      );

  @override
  Future<Uint8List> crateApiTtsSynthesizeOpenaiTts({
    required String text,
    required String voice,
    required String apiKey,
    required double speed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(voice, serializer);
          sse_encode_String(apiKey, serializer);
          sse_encode_f_64(speed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTtsSynthesizeOpenaiTtsConstMeta,
        argValues: [text, voice, apiKey, speed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTtsSynthesizeOpenaiTtsConstMeta =>
      const TaskConstMeta(
        debugName: "synthesize_openai_tts",
        argNames: ["text", "voice", "apiKey", "speed"],
      );

  @override
  Future<Uint8List> crateApiSyncWebdavDownloadBytes({
    required String remotePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remotePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebdavDownloadBytesConstMeta,
        argValues: [remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebdavDownloadBytesConstMeta =>
      const TaskConstMeta(
        debugName: "webdav_download_bytes",
        argNames: ["remotePath"],
      );

  @override
  Future<bool> crateApiSyncWebdavFileExists({required String remotePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remotePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebdavFileExistsConstMeta,
        argValues: [remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebdavFileExistsConstMeta =>
      const TaskConstMeta(
        debugName: "webdav_file_exists",
        argNames: ["remotePath"],
      );

  @override
  Future<void> crateApiSyncWebdavInit({
    required String url,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebdavInitConstMeta,
        argValues: [url, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebdavInitConstMeta => const TaskConstMeta(
    debugName: "webdav_init",
    argNames: ["url", "username", "password"],
  );

  @override
  Future<bool> crateApiSyncWebdavMkdir({required String remotePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remotePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebdavMkdirConstMeta,
        argValues: [remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebdavMkdirConstMeta =>
      const TaskConstMeta(debugName: "webdav_mkdir", argNames: ["remotePath"]);

  @override
  Future<bool> crateApiSyncWebdavRemove({required String remotePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remotePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebdavRemoveConstMeta,
        argValues: [remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebdavRemoveConstMeta =>
      const TaskConstMeta(debugName: "webdav_remove", argNames: ["remotePath"]);

  @override
  Future<bool> crateApiSyncWebdavTestConnection() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebdavTestConnectionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebdavTestConnectionConstMeta =>
      const TaskConstMeta(debugName: "webdav_test_connection", argNames: []);

  @override
  Future<bool> crateApiSyncWebdavUploadBytes({
    required String remotePath,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remotePath, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWebdavUploadBytesConstMeta,
        argValues: [remotePath, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWebdavUploadBytesConstMeta =>
      const TaskConstMeta(
        debugName: "webdav_upload_bytes",
        argNames: ["remotePath", "bytes"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WebDavClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WebDavClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient;

  @protected
  WebDavClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WebDavClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WebDavClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WebDavClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WebDavClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WebDavClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Book dco_decode_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return Book(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      uuid: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      author: dco_decode_String(arr[3]),
      coverPath: dco_decode_opt_String(arr[4]),
      totalChapters: dco_decode_i_32(arr[5]),
      dateAdded: dco_decode_i_64(arr[6]),
      status: dco_decode_String(arr[7]),
      tags: dco_decode_list_String(arr[8]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Book dco_decode_box_autoadd_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_book(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  Chapter dco_decode_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Chapter(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      bookUuid: dco_decode_String(arr[1]),
      chapterIndex: dco_decode_i_32(arr[2]),
      title: dco_decode_String(arr[3]),
      paragraphs: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  EdgeVoice dco_decode_edge_voice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EdgeVoice(
      name: dco_decode_String(arr[0]),
      shortName: dco_decode_String(arr[1]),
      gender: dco_decode_String(arr[2]),
      locale: dco_decode_String(arr[3]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Book> dco_decode_list_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book).toList();
  }

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter).toList();
  }

  @protected
  List<EdgeVoice> dco_decode_list_edge_voice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_edge_voice).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ParsedBookData dco_decode_parsed_book_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ParsedBookData(
      book: dco_decode_book(arr[0]),
      chapters: dco_decode_list_chapter(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WebDavClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WebDavClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WebDavClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WebDavClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WebDavClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WebDavClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Book sse_decode_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_uuid = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_coverPath = sse_decode_opt_String(deserializer);
    var var_totalChapters = sse_decode_i_32(deserializer);
    var var_dateAdded = sse_decode_i_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return Book(
      id: var_id,
      uuid: var_uuid,
      title: var_title,
      author: var_author,
      coverPath: var_coverPath,
      totalChapters: var_totalChapters,
      dateAdded: var_dateAdded,
      status: var_status,
      tags: var_tags,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Book sse_decode_box_autoadd_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_book(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_bookUuid = sse_decode_String(deserializer);
    var var_chapterIndex = sse_decode_i_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_paragraphs = sse_decode_list_String(deserializer);
    return Chapter(
      id: var_id,
      bookUuid: var_bookUuid,
      chapterIndex: var_chapterIndex,
      title: var_title,
      paragraphs: var_paragraphs,
    );
  }

  @protected
  EdgeVoice sse_decode_edge_voice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_shortName = sse_decode_String(deserializer);
    var var_gender = sse_decode_String(deserializer);
    var var_locale = sse_decode_String(deserializer);
    return EdgeVoice(
      name: var_name,
      shortName: var_shortName,
      gender: var_gender,
      locale: var_locale,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Book> sse_decode_list_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Book>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book(deserializer));
    }
    return ans_;
  }

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Chapter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter(deserializer));
    }
    return ans_;
  }

  @protected
  List<EdgeVoice> sse_decode_list_edge_voice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EdgeVoice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_edge_voice(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParsedBookData sse_decode_parsed_book_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_book = sse_decode_book(deserializer);
    var var_chapters = sse_decode_list_chapter(deserializer);
    return ParsedBookData(book: var_book, chapters: var_chapters);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WebDavClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WebDavClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WebDavClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_book(Book self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.uuid, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_opt_String(self.coverPath, serializer);
    sse_encode_i_32(self.totalChapters, serializer);
    sse_encode_i_64(self.dateAdded, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_book(Book self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_book(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.bookUuid, serializer);
    sse_encode_i_32(self.chapterIndex, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.paragraphs, serializer);
  }

  @protected
  void sse_encode_edge_voice(EdgeVoice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.shortName, serializer);
    sse_encode_String(self.gender, serializer);
    sse_encode_String(self.locale, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book(List<Book> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_edge_voice(
    List<EdgeVoice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_edge_voice(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_parsed_book_data(
    ParsedBookData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_book(self.book, serializer);
    sse_encode_list_chapter(self.chapters, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class WebDavClientImpl extends RustOpaque implements WebDavClient {
  // Not to be used by end users
  WebDavClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WebDavClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WebDavClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WebDavClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WebDavClientPtr,
  );

  Future<Uint8List> downloadBytes({required String remotePath}) =>
      RustLib.instance.api.crateApiSyncWebDavClientDownloadBytes(
        that: this,
        remotePath: remotePath,
      );

  Future<bool> fileExists({required String remotePath}) => RustLib.instance.api
      .crateApiSyncWebDavClientFileExists(that: this, remotePath: remotePath);

  Future<bool> mkdir({required String remotePath}) => RustLib.instance.api
      .crateApiSyncWebDavClientMkdir(that: this, remotePath: remotePath);

  Future<bool> remove({required String remotePath}) => RustLib.instance.api
      .crateApiSyncWebDavClientRemove(that: this, remotePath: remotePath);

  Future<bool> testConnection() =>
      RustLib.instance.api.crateApiSyncWebDavClientTestConnection(that: this);

  Future<bool> uploadBytes({
    required String remotePath,
    required List<int> bytes,
  }) => RustLib.instance.api.crateApiSyncWebDavClientUploadBytes(
    that: this,
    remotePath: remotePath,
    bytes: bytes,
  );
}
