// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/database.dart';
import 'api/models.dart';
import 'api/offline_downloader.dart';
import 'api/parsers.dart';
import 'api/simple.dart';
import 'api/supertonic.dart';
import 'api/sync.dart';
import 'api/tts.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WebDavClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClientPtr;

  @protected
  WebDavClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  );

  @protected
  WebDavClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  );

  @protected
  WebDavClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  BgmTrack dco_decode_bgm_track(dynamic raw);

  @protected
  Book dco_decode_book(dynamic raw);

  @protected
  BookStorageInfo dco_decode_book_storage_info(dynamic raw);

  @protected
  Bookmark dco_decode_bookmark(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  BgmTrack dco_decode_box_autoadd_bgm_track(dynamic raw);

  @protected
  Book dco_decode_box_autoadd_book(dynamic raw);

  @protected
  Bookmark dco_decode_box_autoadd_bookmark(dynamic raw);

  @protected
  Highlight dco_decode_box_autoadd_highlight(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  OfflineTtsRecord dco_decode_box_autoadd_offline_tts_record(dynamic raw);

  @protected
  PronunciationRule dco_decode_box_autoadd_pronunciation_rule(dynamic raw);

  @protected
  ReadingProgress dco_decode_box_autoadd_reading_progress(dynamic raw);

  @protected
  Chapter dco_decode_chapter(dynamic raw);

  @protected
  ChapterStorageSize dco_decode_chapter_storage_size(dynamic raw);

  @protected
  DownloadStatusInfo dco_decode_download_status_info(dynamic raw);

  @protected
  EdgeVoice dco_decode_edge_voice(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Highlight dco_decode_highlight(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BgmTrack> dco_decode_list_bgm_track(dynamic raw);

  @protected
  List<Book> dco_decode_list_book(dynamic raw);

  @protected
  List<Bookmark> dco_decode_list_bookmark(dynamic raw);

  @protected
  List<Chapter> dco_decode_list_chapter(dynamic raw);

  @protected
  List<ChapterStorageSize> dco_decode_list_chapter_storage_size(dynamic raw);

  @protected
  List<EdgeVoice> dco_decode_list_edge_voice(dynamic raw);

  @protected
  List<Highlight> dco_decode_list_highlight(dynamic raw);

  @protected
  List<OfflineTtsRecord> dco_decode_list_offline_tts_record(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PronunciationRule> dco_decode_list_pronunciation_rule(dynamic raw);

  @protected
  List<ReadingProgress> dco_decode_list_reading_progress(dynamic raw);

  @protected
  List<WebDavFile> dco_decode_list_web_dav_file(dynamic raw);

  @protected
  OfflineTtsRecord dco_decode_offline_tts_record(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AppSettings? dco_decode_opt_box_autoadd_app_settings(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  OfflineTtsRecord? dco_decode_opt_box_autoadd_offline_tts_record(dynamic raw);

  @protected
  ReadingProgress? dco_decode_opt_box_autoadd_reading_progress(dynamic raw);

  @protected
  ParsedBookData dco_decode_parsed_book_data(dynamic raw);

  @protected
  PronunciationRule dco_decode_pronunciation_rule(dynamic raw);

  @protected
  ReadingProgress dco_decode_reading_progress(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WebDavFile dco_decode_web_dav_file(dynamic raw);

  @protected
  WebDavClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  );

  @protected
  WebDavClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  );

  @protected
  WebDavClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  BgmTrack sse_decode_bgm_track(SseDeserializer deserializer);

  @protected
  Book sse_decode_book(SseDeserializer deserializer);

  @protected
  BookStorageInfo sse_decode_book_storage_info(SseDeserializer deserializer);

  @protected
  Bookmark sse_decode_bookmark(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  BgmTrack sse_decode_box_autoadd_bgm_track(SseDeserializer deserializer);

  @protected
  Book sse_decode_box_autoadd_book(SseDeserializer deserializer);

  @protected
  Bookmark sse_decode_box_autoadd_bookmark(SseDeserializer deserializer);

  @protected
  Highlight sse_decode_box_autoadd_highlight(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  OfflineTtsRecord sse_decode_box_autoadd_offline_tts_record(
    SseDeserializer deserializer,
  );

  @protected
  PronunciationRule sse_decode_box_autoadd_pronunciation_rule(
    SseDeserializer deserializer,
  );

  @protected
  ReadingProgress sse_decode_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  Chapter sse_decode_chapter(SseDeserializer deserializer);

  @protected
  ChapterStorageSize sse_decode_chapter_storage_size(
    SseDeserializer deserializer,
  );

  @protected
  DownloadStatusInfo sse_decode_download_status_info(
    SseDeserializer deserializer,
  );

  @protected
  EdgeVoice sse_decode_edge_voice(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Highlight sse_decode_highlight(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BgmTrack> sse_decode_list_bgm_track(SseDeserializer deserializer);

  @protected
  List<Book> sse_decode_list_book(SseDeserializer deserializer);

  @protected
  List<Bookmark> sse_decode_list_bookmark(SseDeserializer deserializer);

  @protected
  List<Chapter> sse_decode_list_chapter(SseDeserializer deserializer);

  @protected
  List<ChapterStorageSize> sse_decode_list_chapter_storage_size(
    SseDeserializer deserializer,
  );

  @protected
  List<EdgeVoice> sse_decode_list_edge_voice(SseDeserializer deserializer);

  @protected
  List<Highlight> sse_decode_list_highlight(SseDeserializer deserializer);

  @protected
  List<OfflineTtsRecord> sse_decode_list_offline_tts_record(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PronunciationRule> sse_decode_list_pronunciation_rule(
    SseDeserializer deserializer,
  );

  @protected
  List<ReadingProgress> sse_decode_list_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  List<WebDavFile> sse_decode_list_web_dav_file(SseDeserializer deserializer);

  @protected
  OfflineTtsRecord sse_decode_offline_tts_record(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AppSettings? sse_decode_opt_box_autoadd_app_settings(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  OfflineTtsRecord? sse_decode_opt_box_autoadd_offline_tts_record(
    SseDeserializer deserializer,
  );

  @protected
  ReadingProgress? sse_decode_opt_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  ParsedBookData sse_decode_parsed_book_data(SseDeserializer deserializer);

  @protected
  PronunciationRule sse_decode_pronunciation_rule(SseDeserializer deserializer);

  @protected
  ReadingProgress sse_decode_reading_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WebDavFile sse_decode_web_dav_file(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    WebDavClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bgm_track(BgmTrack self, SseSerializer serializer);

  @protected
  void sse_encode_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_book_storage_info(
    BookStorageInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bookmark(Bookmark self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bgm_track(
    BgmTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_book(Book self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bookmark(Bookmark self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_highlight(
    Highlight self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_offline_tts_record(
    OfflineTtsRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pronunciation_rule(
    PronunciationRule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter(Chapter self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_storage_size(
    ChapterStorageSize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_status_info(
    DownloadStatusInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edge_voice(EdgeVoice self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_highlight(Highlight self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bgm_track(List<BgmTrack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_book(List<Book> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bookmark(List<Bookmark> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter(List<Chapter> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_storage_size(
    List<ChapterStorageSize> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_edge_voice(
    List<EdgeVoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_highlight(
    List<Highlight> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_offline_tts_record(
    List<OfflineTtsRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pronunciation_rule(
    List<PronunciationRule> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reading_progress(
    List<ReadingProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_web_dav_file(
    List<WebDavFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_offline_tts_record(
    OfflineTtsRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_app_settings(
    AppSettings? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_offline_tts_record(
    OfflineTtsRecord? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reading_progress(
    ReadingProgress? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parsed_book_data(
    ParsedBookData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pronunciation_rule(
    PronunciationRule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_web_dav_file(WebDavFile self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_audire_reader_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_audire_reader_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWebDavClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
