platform :ios, '16.0'

# CocoaPods analytics sends usage stats so we know if we're breaking things.
# Uncomment this line to disable keeping track of analytics.
# disable_cocoapods_analytics!

flutter_ios_podfile_setup = File.join(File.dirname(__FILE__), 'Flutter', 'flutter_export_environment.sh')
if File.exist?(flutter_ios_podfile_setup)
  load File.join(File.dirname(__FILE__), 'Flutter', 'flutter_export_environment.sh')
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(__FILE__)

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
