// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_conn`, `run_migrations`

void initDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiDatabaseInitDatabase(dbPath: dbPath);

Future<List<Book>> getAllBooks() =>
    RustLib.instance.api.crateApiDatabaseGetAllBooks();

Future<PlatformInt64> insertBook({required Book book}) =>
    RustLib.instance.api.crateApiDatabaseInsertBook(book: book);

Future<void> deleteBook({required String uuid}) =>
    RustLib.instance.api.crateApiDatabaseDeleteBook(uuid: uuid);

Future<List<Chapter>> getChapters({required String bookUuid}) =>
    RustLib.instance.api.crateApiDatabaseGetChapters(bookUuid: bookUuid);

Future<void> insertChapters({required List<Chapter> chapters}) =>
    RustLib.instance.api.crateApiDatabaseInsertChapters(chapters: chapters);
