// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `default_close_action`, `default_font_weight`, `default_grid`, `default_true`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BookBookmarksFile`, `BookHighlightsFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class AppSettings with _$AppSettings {
  const factory AppSettings({
    required PlatformInt64 id,
    required double fontSize,
    required double speechRate,
    String? selectedVoiceName,
    String? selectedVoiceLocale,
    required String ttsProvider,
    required String openAiTtsEndpoint,
    required String openAiTtsApiKey,
    required String openAiTtsModel,
    required int ttsDownloadConcurrency,
    required String fontFamily,
    required String fontWeight,
    required String themeMode,
    required String appLocale,
    required double lineHeight,
    required double paragraphSpacing,
    required double paragraphIndent,
    required String textAlignment,
    required double sideMargin,
    String? customBackgroundColor,
    String? customTextColor,
    String? primaryColorHex,
    required bool webDavEnabled,
    required bool webDavAutoSync,
    required String webDavUrl,
    required String webDavUsername,
    PlatformInt64? webDavLastSync,
    String? deviceId,
    String? deviceName,
    required bool openLastReadOnLaunch,
    required String hotkeyNextParagraph,
    required String hotkeyPrevParagraph,
    required String hotkeyNextChapter,
    required String hotkeyPrevChapter,
    required String hotkeyPlayPauseTts,
    required String hotkeyOpenChapter,
    required String hotkeyOpenSetting,
    required String hotkeyBossKey,
    required String bossKeyAction,
    required bool autoCheckUpdate,
    required bool bgmEnabled,
    required double bgmVolume,
    int? currentBgmTrackId,
    String? currentBgmTrackUrl,
    String? currentBgmTrackName,
    required String bgmLoopMode,
    required String bgmProviderId,
    String? lastLocalTrackUrl,
    String? lastRadioTrackUrl,
    String? lastRadioTrackName,
    String? lastLofiTrackUrl,
    String? lastLofiTrackName,
    required String sortBy,
    required bool showAssistiveButton,
    required double assistiveButtonX,
    required double assistiveButtonY,
    required String assistiveSingleTapAction,
    required String assistiveDoubleTapAction,
    required String assistiveLongPressAction,
    required bool developerMode,
    required bool enableDebugLogs,
    required bool enableWebDavDebug,
    required bool audioPanelCollapsed,
    required String libraryViewMode,
    required List<String> searchHistory,
    required String closeAction,
  }) = _AppSettings;
}

@freezed
sealed class BgmTrack with _$BgmTrack {
  const factory BgmTrack({
    PlatformInt64? id,
    required String name,
    required String sourceType,
    required String sourcePath,
    required PlatformInt64 dateAdded,
  }) = _BgmTrack;
}

@freezed
sealed class Book with _$Book {
  const factory Book({
    PlatformInt64? id,
    required String uuid,
    required String title,
    required String author,
    String? coverPath,
    required int totalChapters,
    required PlatformInt64 dateAdded,
    required String status,
    required List<String> tags,
  }) = _Book;
}

@freezed
sealed class Bookmark with _$Bookmark {
  const factory Bookmark({
    PlatformInt64? id,
    required String bookUuid,
    required int chapterIndex,
    required int paragraphIndex,
    required String contentSnippet,
    required PlatformInt64 dateAdded,
  }) = _Bookmark;
}

@freezed
sealed class Chapter with _$Chapter {
  const factory Chapter({
    PlatformInt64? id,
    required String bookUuid,
    required int chapterIndex,
    required String title,
    required List<String> paragraphs,
  }) = _Chapter;
}

@freezed
sealed class CloudBook with _$CloudBook {
  const factory CloudBook({
    required String uuid,
    required String title,
    required String author,
    required int totalChapters,
    String? coverExtension,
    required bool hasCover,
    required String dateAdded,
  }) = _CloudBook;
}

@freezed
sealed class Highlight with _$Highlight {
  const factory Highlight({
    PlatformInt64? id,
    required String bookUuid,
    required int chapterIndex,
    required int paragraphIndex,
    int? startOffset,
    int? endOffset,
    required String text,
    required String colorHex,
    String? note,
    required PlatformInt64 dateAdded,
  }) = _Highlight;
}

@freezed
sealed class OfflineTtsRecord with _$OfflineTtsRecord {
  const factory OfflineTtsRecord({
    PlatformInt64? id,
    required String bookUuid,
    required int chapterIndex,
    required String ttsProvider,
    required String voiceName,
    required double speechRate,
    required bool isCompleted,
    required int totalParagraphs,
    required int downloadedParagraphs,
    required PlatformInt64 totalSizeBytes,
    required PlatformInt64 downloadedAt,
  }) = _OfflineTtsRecord;
}

@freezed
sealed class ProgressSyncResult with _$ProgressSyncResult {
  const factory ProgressSyncResult({
    required String status,
    int? cloudChapterIndex,
    int? cloudParagraphIndex,
    int? cloudCharacterOffset,
    PlatformInt64? cloudLastRead,
    String? message,
  }) = _ProgressSyncResult;
}

@freezed
sealed class PronunciationRule with _$PronunciationRule {
  const factory PronunciationRule({
    PlatformInt64? id,
    required String target,
    required String replacement,
    required bool isRegex,
    required bool active,
  }) = _PronunciationRule;
}

@freezed
sealed class ReadingProgress with _$ReadingProgress {
  const factory ReadingProgress({
    PlatformInt64? id,
    required String bookUuid,
    required int currentChapterIndex,
    required int currentParagraphIndex,
    required int currentCharacterOffset,
    required PlatformInt64 lastRead,
  }) = _ReadingProgress;
}

@freezed
sealed class SyncHistoryEntry with _$SyncHistoryEntry {
  const factory SyncHistoryEntry({
    PlatformInt64? id,
    required PlatformInt64 timestamp,
    required String action,
    required String status,
    required String details,
  }) = _SyncHistoryEntry;
}

@freezed
sealed class SyncProgressEvent with _$SyncProgressEvent {
  const factory SyncProgressEvent({
    required String eventType,
    String? bookUuid,
    String? status,
    required int current,
    required int total,
    String? message,
  }) = _SyncProgressEvent;
}

@freezed
sealed class SyncResult with _$SyncResult {
  const factory SyncResult({
    required bool success,
    required String message,
    required bool localChanged,
  }) = _SyncResult;
}
