// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppSettings`, `Bookmark`, `Highlight`, `ReadingProgress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class Book with _$Book {
  const factory Book({
    PlatformInt64? id,
    required String uuid,
    required String title,
    required String author,
    String? coverPath,
    required int totalChapters,
    required PlatformInt64 dateAdded,
    required String status,
    required List<String> tags,
  }) = _Book;
}

@freezed
sealed class Chapter with _$Chapter {
  const factory Chapter({
    PlatformInt64? id,
    required String bookUuid,
    required int chapterIndex,
    required String title,
    required List<String> paragraphs,
  }) = _Chapter;
}
