// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `log_to_file`, `push_log`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TaskItem`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<void> pauseOfflineDownload() =>
    RustLib.instance.api.crateApiOfflineDownloaderPauseOfflineDownload();

Future<void> resumeOfflineDownload() =>
    RustLib.instance.api.crateApiOfflineDownloaderResumeOfflineDownload();

Future<void> cancelOfflineDownload() =>
    RustLib.instance.api.crateApiOfflineDownloaderCancelOfflineDownload();

Future<bool> isDownloadRunning() =>
    RustLib.instance.api.crateApiOfflineDownloaderIsDownloadRunning();

/// Scan disk in < 2ms to verify real audio files, total bytes, and size per chapter
Future<BookStorageInfo> getBookStorageInfo({
  required String baseDir,
  required String bookUuid,
}) => RustLib.instance.api.crateApiOfflineDownloaderGetBookStorageInfo(
  baseDir: baseDir,
  bookUuid: bookUuid,
);

Future<DownloadStatusInfo> getDownloadStatus({
  required String baseDir,
  required String bookUuid,
}) => RustLib.instance.api.crateApiOfflineDownloaderGetDownloadStatus(
  baseDir: baseDir,
  bookUuid: bookUuid,
);

Future<void> startOfflineDownloadJob({
  required String bookUuid,
  required List<int> chapterIndices,
  required BigInt concurrency,
  required String baseDir,
  required String provider,
  required String voiceName,
  required double speechRate,
  String? openaiApiKey,
}) => RustLib.instance.api.crateApiOfflineDownloaderStartOfflineDownloadJob(
  bookUuid: bookUuid,
  chapterIndices: chapterIndices,
  concurrency: concurrency,
  baseDir: baseDir,
  provider: provider,
  voiceName: voiceName,
  speechRate: speechRate,
  openaiApiKey: openaiApiKey,
);

class BookStorageInfo {
  final BigInt totalBytes;
  final Int32List chapterIndices;
  final List<ChapterStorageSize> chapterSizes;

  const BookStorageInfo({
    required this.totalBytes,
    required this.chapterIndices,
    required this.chapterSizes,
  });

  @override
  int get hashCode =>
      totalBytes.hashCode ^ chapterIndices.hashCode ^ chapterSizes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookStorageInfo &&
          runtimeType == other.runtimeType &&
          totalBytes == other.totalBytes &&
          chapterIndices == other.chapterIndices &&
          chapterSizes == other.chapterSizes;
}

class ChapterStorageSize {
  final int chapterIndex;
  final BigInt bytes;

  const ChapterStorageSize({required this.chapterIndex, required this.bytes});

  @override
  int get hashCode => chapterIndex.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterStorageSize &&
          runtimeType == other.runtimeType &&
          chapterIndex == other.chapterIndex &&
          bytes == other.bytes;
}

class DownloadStatusInfo {
  final bool isRunning;
  final bool isPaused;
  final BigInt totalChapters;
  final BigInt completedChapters;
  final BigInt totalBytes;
  final Int32List activeChapterIndices;
  final Int32List downloadedChapterIndices;
  final Int32List failedChapterIndices;
  final List<ChapterStorageSize> chapterSizes;
  final List<String> recentLogs;

  const DownloadStatusInfo({
    required this.isRunning,
    required this.isPaused,
    required this.totalChapters,
    required this.completedChapters,
    required this.totalBytes,
    required this.activeChapterIndices,
    required this.downloadedChapterIndices,
    required this.failedChapterIndices,
    required this.chapterSizes,
    required this.recentLogs,
  });

  @override
  int get hashCode =>
      isRunning.hashCode ^
      isPaused.hashCode ^
      totalChapters.hashCode ^
      completedChapters.hashCode ^
      totalBytes.hashCode ^
      activeChapterIndices.hashCode ^
      downloadedChapterIndices.hashCode ^
      failedChapterIndices.hashCode ^
      chapterSizes.hashCode ^
      recentLogs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadStatusInfo &&
          runtimeType == other.runtimeType &&
          isRunning == other.isRunning &&
          isPaused == other.isPaused &&
          totalChapters == other.totalChapters &&
          completedChapters == other.completedChapters &&
          totalBytes == other.totalBytes &&
          activeChapterIndices == other.activeChapterIndices &&
          downloadedChapterIndices == other.downloadedChapterIndices &&
          failedChapterIndices == other.failedChapterIndices &&
          chapterSizes == other.chapterSizes &&
          recentLogs == other.recentLogs;
}
