// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean_and_merge_lines`, `parse_html_to_paragraphs`, `sanitize_text`, `segment_fallback`, `segment_text_into_chapters`

ParsedBookData parseTxtFile({required String filePath}) =>
    RustLib.instance.api.crateApiParsersParseTxtFile(filePath: filePath);

ParsedBookData parsePdfFile({required String filePath}) =>
    RustLib.instance.api.crateApiParsersParsePdfFile(filePath: filePath);

ParsedBookData parseDocxFile({required String filePath}) =>
    RustLib.instance.api.crateApiParsersParseDocxFile(filePath: filePath);

ParsedBookData parseEpubFile({
  required String filePath,
  required String documentsDirPath,
}) => RustLib.instance.api.crateApiParsersParseEpubFile(
  filePath: filePath,
  documentsDirPath: documentsDirPath,
);

class ParsedBookData {
  final Book book;
  final List<Chapter> chapters;

  const ParsedBookData({required this.book, required this.chapters});

  @override
  int get hashCode => book.hashCode ^ chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedBookData &&
          runtimeType == other.runtimeType &&
          book == other.book &&
          chapters == other.chapters;
}
