// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `array1_f32_to_value`, `array2_f32_to_value`, `array2_i64_to_value`, `array3_f32_to_value`, `process_unicode_indexer`, `sample_noisy_latent`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SupertonicState`

Future<bool> isValidLang({required String lang}) =>
    RustLib.instance.api.crateApiSupertonicIsValidLang(lang: lang);

Future<String> detectLanguage({required String text}) =>
    RustLib.instance.api.crateApiSupertonicDetectLanguage(text: text);

Future<String> preprocessText({required String text, required String lang}) =>
    RustLib.instance.api.crateApiSupertonicPreprocessText(
      text: text,
      lang: lang,
    );

Future<List<String>> chunkText({
  required String text,
  required BigInt maxLen,
}) => RustLib.instance.api.crateApiSupertonicChunkText(
  text: text,
  maxLen: maxLen,
);

Future<Uint8List> encodeWav({
  required List<double> audioData,
  required int sampleRate,
}) => RustLib.instance.api.crateApiSupertonicEncodeWav(
  audioData: audioData,
  sampleRate: sampleRate,
);

Future<bool> checkSupertonicModelExists({required String baseDir}) => RustLib
    .instance
    .api
    .crateApiSupertonicCheckSupertonicModelExists(baseDir: baseDir);

Future<void> deleteSupertonicModels({required String baseDir}) => RustLib
    .instance
    .api
    .crateApiSupertonicDeleteSupertonicModels(baseDir: baseDir);

Future<void> downloadSupertonicModels({required String baseDir}) => RustLib
    .instance
    .api
    .crateApiSupertonicDownloadSupertonicModels(baseDir: baseDir);

Future<bool> initSupertonicEngine({
  required String baseDir,
  required String voiceStyle,
}) => RustLib.instance.api.crateApiSupertonicInitSupertonicEngine(
  baseDir: baseDir,
  voiceStyle: voiceStyle,
);

Future<void> releaseSupertonicEngine() =>
    RustLib.instance.api.crateApiSupertonicReleaseSupertonicEngine();

Future<Uint8List> synthesizeSupertonic({
  required String text,
  required String lang,
  required double speed,
  required int denoiseSteps,
}) => RustLib.instance.api.crateApiSupertonicSynthesizeSupertonic(
  text: text,
  lang: lang,
  speed: speed,
  denoiseSteps: denoiseSteps,
);
