// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_sync_event`, `headers`, `parse_webdav_xml`, `record_book_progress_sync`, `uuid`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SyncBookPayload`, `SyncChapterPayload`, `SyncDataBookItem`, `SyncDataFile`, `SyncDeletedItem`, `SyncProgressPayload`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<void> saveWebdavPassword({required String password}) =>
    RustLib.instance.api.crateApiSyncSaveWebdavPassword(password: password);

Future<String?> getWebdavPassword() =>
    RustLib.instance.api.crateApiSyncGetWebdavPassword();

Future<void> deleteWebdavPassword() =>
    RustLib.instance.api.crateApiSyncDeleteWebdavPassword();

Stream<SyncProgressEvent> subscribeSyncEvents() =>
    RustLib.instance.api.crateApiSyncSubscribeSyncEvents();

Future<void> saveWebdavConfig({
  required String url,
  required String username,
  String? password,
}) => RustLib.instance.api.crateApiSyncSaveWebdavConfig(
  url: url,
  username: username,
  password: password,
);

Future<WebDavClient> getOrInitClient() =>
    RustLib.instance.api.crateApiSyncGetOrInitClient();

Future<bool> testWebdavConnection({
  String? url,
  String? username,
  String? password,
}) => RustLib.instance.api.crateApiSyncTestWebdavConnection(
  url: url,
  username: username,
  password: password,
);

Future<bool> exportAndUploadBook({required String bookUuid}) =>
    RustLib.instance.api.crateApiSyncExportAndUploadBook(bookUuid: bookUuid);

Future<Book> downloadAndImportBook({
  required String bookUuid,
  required String documentsDir,
}) => RustLib.instance.api.crateApiSyncDownloadAndImportBook(
  bookUuid: bookUuid,
  documentsDir: documentsDir,
);

Future<List<CloudBook>> fetchCloudBooks({String? documentsDir}) => RustLib
    .instance
    .api
    .crateApiSyncFetchCloudBooks(documentsDir: documentsDir);

Future<ProgressSyncResult> syncBookProgress({required String bookUuid}) =>
    RustLib.instance.api.crateApiSyncSyncBookProgress(bookUuid: bookUuid);

Future<bool> syncBookBookmarks({required String bookUuid}) =>
    RustLib.instance.api.crateApiSyncSyncBookBookmarks(bookUuid: bookUuid);

Future<bool> syncBookHighlights({required String bookUuid}) =>
    RustLib.instance.api.crateApiSyncSyncBookHighlights(bookUuid: bookUuid);

Future<SyncResult> syncLibrary({String? documentsDir}) =>
    RustLib.instance.api.crateApiSyncSyncLibrary(documentsDir: documentsDir);

Future<SyncResult> syncAll({String? documentsDir}) =>
    RustLib.instance.api.crateApiSyncSyncAll(documentsDir: documentsDir);

Future<SyncResult> forcePush({required bool progressOnly}) =>
    RustLib.instance.api.crateApiSyncForcePush(progressOnly: progressOnly);

Future<SyncResult> forcePull({
  required bool progressOnly,
  required String documentsDir,
}) => RustLib.instance.api.crateApiSyncForcePull(
  progressOnly: progressOnly,
  documentsDir: documentsDir,
);

Future<SyncResult> forcePushBook({required String bookUuid}) =>
    RustLib.instance.api.crateApiSyncForcePushBook(bookUuid: bookUuid);

Future<SyncResult> forcePullBook({
  required String bookUuid,
  required String documentsDir,
}) => RustLib.instance.api.crateApiSyncForcePullBook(
  bookUuid: bookUuid,
  documentsDir: documentsDir,
);

Future<SyncResult> deleteBookFromCloud({required String bookUuid}) =>
    RustLib.instance.api.crateApiSyncDeleteBookFromCloud(bookUuid: bookUuid);

Future<SyncResult> uploadSingleBook({required String bookUuid}) =>
    RustLib.instance.api.crateApiSyncUploadSingleBook(bookUuid: bookUuid);

Future<SyncResult> downloadVirtualBook({
  required String bookUuid,
  required String documentsDir,
}) => RustLib.instance.api.crateApiSyncDownloadVirtualBook(
  bookUuid: bookUuid,
  documentsDir: documentsDir,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WebDavClient>>
abstract class WebDavClient implements RustOpaqueInterface {
  Future<Uint8List> downloadBytes({required String remotePath});

  Future<bool> downloadFile({
    required String remotePath,
    required String localPath,
  });

  Future<bool> fileExists({required String remotePath});

  Future<List<WebDavFile>> listFiles({required String remotePath});

  Future<bool> mkdir({required String remotePath});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WebDavClient> newInstance({
    required String url,
    required String user,
    required String pass,
  }) => RustLib.instance.api.crateApiSyncWebDavClientNew(
    url: url,
    user: user,
    pass: pass,
  );

  Future<bool> remove({required String remotePath});

  Future<bool> testConnection();

  Future<bool> uploadBytes({
    required String remotePath,
    required List<int> bytes,
  });

  Future<bool> uploadFile({
    required String remotePath,
    required String localPath,
  });
}

class WebDavFile {
  final String name;
  final String path;
  final bool isDir;
  final PlatformInt64 size;
  final String lastModified;

  const WebDavFile({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
    required this.lastModified,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size &&
          lastModified == other.lastModified;
}
