// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `headers`, `parse_webdav_xml`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> webdavInit({
  required String url,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSyncWebdavInit(
  url: url,
  username: username,
  password: password,
);

Future<bool> webdavTestConnection() =>
    RustLib.instance.api.crateApiSyncWebdavTestConnection();

Future<bool> webdavMkdir({required String remotePath}) =>
    RustLib.instance.api.crateApiSyncWebdavMkdir(remotePath: remotePath);

Future<bool> webdavUploadBytes({
  required String remotePath,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiSyncWebdavUploadBytes(
  remotePath: remotePath,
  bytes: bytes,
);

Future<bool> webdavUploadFile({
  required String remotePath,
  required String localPath,
}) => RustLib.instance.api.crateApiSyncWebdavUploadFile(
  remotePath: remotePath,
  localPath: localPath,
);

Future<Uint8List> webdavDownloadBytes({required String remotePath}) => RustLib
    .instance
    .api
    .crateApiSyncWebdavDownloadBytes(remotePath: remotePath);

Future<bool> webdavDownloadFile({
  required String remotePath,
  required String localPath,
}) => RustLib.instance.api.crateApiSyncWebdavDownloadFile(
  remotePath: remotePath,
  localPath: localPath,
);

Future<List<WebDavFile>> webdavListFiles({required String remotePath}) =>
    RustLib.instance.api.crateApiSyncWebdavListFiles(remotePath: remotePath);

Future<bool> webdavRemove({required String remotePath}) =>
    RustLib.instance.api.crateApiSyncWebdavRemove(remotePath: remotePath);

Future<bool> webdavFileExists({required String remotePath}) =>
    RustLib.instance.api.crateApiSyncWebdavFileExists(remotePath: remotePath);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WebDavClient>>
abstract class WebDavClient implements RustOpaqueInterface {
  Future<Uint8List> downloadBytes({required String remotePath});

  Future<bool> downloadFile({
    required String remotePath,
    required String localPath,
  });

  Future<bool> fileExists({required String remotePath});

  Future<List<WebDavFile>> listFiles({required String remotePath});

  Future<bool> mkdir({required String remotePath});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WebDavClient> newInstance({
    required String url,
    required String user,
    required String pass,
  }) => RustLib.instance.api.crateApiSyncWebDavClientNew(
    url: url,
    user: user,
    pass: pass,
  );

  Future<bool> remove({required String remotePath});

  Future<bool> testConnection();

  Future<bool> uploadBytes({
    required String remotePath,
    required List<int> bytes,
  });

  Future<bool> uploadFile({
    required String remotePath,
    required String localPath,
  });
}

class WebDavFile {
  final String name;
  final String path;
  final bool isDir;
  final PlatformInt64 size;
  final String lastModified;

  const WebDavFile({
    required this.name,
    required this.path,
    required this.isDir,
    required this.size,
    required this.lastModified,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDir.hashCode ^
      size.hashCode ^
      lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebDavFile &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDir == other.isDir &&
          size == other.size &&
          lastModified == other.lastModified;
}
