// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_rate`, `current_time_ms`, `get_token`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EdgeToken`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<EdgeVoice>> getEdgeVoices() =>
    RustLib.instance.api.crateApiTtsGetEdgeVoices();

Future<Uint8List> synthesizeEdgeTts({
  required String text,
  required String voiceId,
  required double rate,
}) => RustLib.instance.api.crateApiTtsSynthesizeEdgeTts(
  text: text,
  voiceId: voiceId,
  rate: rate,
);

Future<Uint8List> synthesizeOpenaiTts({
  required String text,
  required String voice,
  required String apiKey,
  required double speed,
}) => RustLib.instance.api.crateApiTtsSynthesizeOpenaiTts(
  text: text,
  voice: voice,
  apiKey: apiKey,
  speed: speed,
);

Future<bool> initOfflineTts() =>
    RustLib.instance.api.crateApiTtsInitOfflineTts();

Future<bool> offlineTtsSpeak({required String text, required double rate}) =>
    RustLib.instance.api.crateApiTtsOfflineTtsSpeak(text: text, rate: rate);

Future<bool> offlineTtsStop() =>
    RustLib.instance.api.crateApiTtsOfflineTtsStop();

class EdgeVoice {
  final String name;
  final String shortName;
  final String gender;
  final String locale;

  const EdgeVoice({
    required this.name,
    required this.shortName,
    required this.gender,
    required this.locale,
  });

  @override
  int get hashCode =>
      name.hashCode ^ shortName.hashCode ^ gender.hashCode ^ locale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EdgeVoice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          shortName == other.shortName &&
          gender == other.gender &&
          locale == other.locale;
}
